name: hide_and_seek_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flame: ^1.28.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/characters/hider.png
    - assets/characters/seeker.png
    - assets/maps/room1.png
    - assets/maps/room2.png
