name: SonarQube Flutter Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Requerido por SonarQube

      - name: Remove Flutter cache if exists
        run: |
          if (Test-Path "$env:USERPROFILE\.flutter") {
            Remove-Item -Recurse -Force "$env:USERPROFILE\.flutter"
          }

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Dart >= 3.7.2 incluido

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze the project
        run: flutter analyze

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
